### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by siers** [sgraf812/pomaps#4]
(This might serve only as a piece of documentation, if you're not interested in fixing this.)

Although I know POSet will be slower than a Set in general, I don't think it should've become the bottle-neck. I also can provide the raw, meaty example repo of POSet usage, which with other dependencies declared in `shell.nix`/`.cabal`.

```
	Mon Feb  8 12:48 2021 Time and Allocation Profiling Report  (Final)

	   solve +RTS -p -RTS samples/4-1

	total time  =        6.42 secs   (6423 ticks @ 1000 us, 1 processor)
	total alloc = 6,359,134,232 bytes  (excludes profiling overheads)

COST CENTRE            MODULE              SRC                                          %time %alloc

leq                    Main                solve.hs:101:3-108                            33.4    0.0
alterWithKey           Data.POMap.Internal src/Data/POMap/Internal.hs:(557,1)-(565,56)   30.7   60.3
dedupAntichain         Data.POMap.Internal src/Data/POMap/Internal.hs:273:1-49            6.1    5.3
allM                   Control.Monad.Extra src/Control/Monad/Extra.hs:235:1-38            3.2    4.9
ifM                    Control.Monad.Extra src/Control/Monad/Extra.hs:195:1-41            2.4    2.7
mazeBounded            Main                solve.hs:138:1-87                              2.2    2.6
addNextContinues       Main                solve.hs:(379,1)-(383,48)                      2.1    1.2
mazeDeltas             Main                solve.hs:(320,1)-(323,66)                      1.7    2.3
partEquate.find        Main                solve.hs:189:5-95                              1.6    2.8
verify.partFollow      Main                solve.hs:(461,5)-(470,69)                      1.3    1.0
solve'                 Main                solve.hs:(431,1)-(447,63)                      1.1    0.6
solveContinue          Main                solve.hs:(403,1)-(417,54)                      1.0    1.0
pieceRotationCount     Main                solve.hs:(363,1)-(365,77)                      1.0    1.4
cursorDelta            Main                solve.hs:(313,1)-(317,60)                      1.0    0.9
pieceDead.discontinued Main                solve.hs:(395,5)-(397,87)                      0.8    1.4
lookupMin              Data.POMap.Internal src/Data/POMap/Internal.hs:1327:1-87           0.5    1.6
```
[solve.prof.txt](https://github.com/sgraf812/pomaps/files/5943635/solve.prof.txt)

**Comment by sgraf812** [comment]
Well, I agree with that sentiment. But I'm not sure how to speed it up, at least not without ideas about a more efficient data structure. I'm open to pull requests in that area.

What kind of workload is your benchmark about? Does it modify the Set?

**Comment by siers** [comment]
Yeah, modifications happen all the time and are very central, because it's used as a priority queue for next choices. A few inserts, a few deletions and dequeuing through `delete (head (lookupMin set)))` and round it goes...

**Comment by siers** [comment]
Isn't it odd that `leq` is so high up?

Here are my instances:
```haskell
instance Eq Continue where
  Continue{cursor=ca, score=sa} == Continue{cursor=cb, score=sb} = ca == cb && sa == sb

instance PartialOrd Continue where
  Continue{cursor=ca, score=sa} `leq` Continue{cursor=cb, score=sb} = if sa == sb then ca == cb else sa < sb
```

**Comment by sgraf812** [comment]
Since `score` is totally ordered, I think it might make sense to use `Map Score [Cursor]` instead. You could even use an `IntMap` if `Score` is an `Int`... Which would be way faster.

I don't see how I can exploit similar domain specific knowledge about the `PartialOrd` instance in the implementation of `POMap`.

Although I must say that `leq` taking so much time is either a good sign (not much overhead of the data structure) or a bad sign (too man `leq` queries). It's a bit hard to tell just from the profile.

**Comment by siers** [comment]
I read up on Dilworth's theorem and I understand that you're storing chains. I assumed that antichain partitions are probably used – I have a suspicion this might be faster in this case. (I hope that makes sense mathematically.)

Anyway, then I guess there might be no problem. :) Feel free to close the issue.

**Comment by sgraf812** [comment]
> I assumed that antichain partitions are probably used – I have a suspicion this might be faster in this case. (I hope that makes sense mathematically.)

Hmm, so basically store `Map [k] [v]` instead of `[Map k v]`. But then each lookup in the outer `Map` needs to compare the key to `O(w)` `k`s on each internal tree node, `log n` times. So still `O(w*log n)`, but maybe with more favorable constants? Not sure. Anyway, I'm not so keen about implementing that just for an experiment. But feel free to explore! I'd be happy to change the implementation if that turns out to be more performant. 

But I suspect that the performance likely won't get better for arbitrary partial orders. It will still be much more performant to realise a lexicographical order on `k` if there is one, like in your example.
